[workspace]
members = [
    "crates/endive-engine",
    "crates/endive-kernel",
    "crates/endive-lambda",
    "crates/endive-parse",
    "crates/endive-print",
    "crates/endive-stmt",
    "crates/endive-wasm",
]
resolver = "2"
