[package]
name = "endive-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
endive-kernel = { path = "../endive-kernel" }
endive-lambda = { path = "../endive-lambda" }
endive-print = { path = "../endive-print" }
