// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Source = 2,
  Block = 3,
  Declaration = 4,
  Lemma = 5,
  Identifier = 6,
  Expression = 7,
  Value = 8,
  Keyword = 9,
  Number = 10,
  Binop = 11,
  Type = 12,
  Action = 13,
  Tactic = 14
