// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
const spec_Identifier = {
  __proto__: null,
  Lemma: 44,
  Exercise: 46,
  Qed: 48,
  forall: 52,
  exists: 54,
  pouet: 56,
  Prop: 58,
  Set: 60,
  exact: 64,
  let: 66,
};
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "&xQYQPOOOOQO'#Ca'#CaOeQPO'#C`OmQPO'#C_OOQO'#Ck'#CkQYQPOOO!OQPO,58zO!^QPO,58zO!cQPO,58yOOQO'#Ci'#CiO!nQPO'#ChOOQO'#Cl'#ClO!vQPO,58yOOQO-E6i-E6iOOQO'#Ce'#CeO#XQPO'#CdOOQO'#Cd'#CdO#dQPO'#CcO#lQPO1G.fO!OQPO1G.fOOQO'#Cj'#CjOOQO1G.e1G.eO#qQPO'#CmO#|QPO,59SOOQO,59S,59SO!cQPO1G.eOOQO-E6j-E6jO$UQPO,58}O!OQPO,58}OOQO7+$Q7+$QO$^QPO7+$QO$cQPO,59XOOQO-E6k-E6kOOQO1G.n1G.nOOQO7+$P7+$PO!OQPO1G.iO$nQPO1G.iOOQO1G.i1G.iOOQO<<Gl<<GlOOQO'#Cg'#CgOOQO1G.s1G.sOOQO7+$T7+$TO$yQPO7+$TO!OQPO<<GoOOQOAN=ZAN=Z",
  stateData:
    "%O~OdOSPOS~OfPOgPOhPO~OUVOiUO~OfPOgPOhWOpXOqXO~OU`Oj^Ok^Ol^O~OicO~OedOUTXiTX~OUfOehO~OfPOgPOhiOpXOqXO~OUkOYWXeWX~OYlOeVX~OemO~OioOUaXeaX~OUfOeqO~OitOosO~OevO~OUxOmwOnwO~OUzOmwOnwO~Oo{O~O",
  goto: "#YbPPPckqPw!W!_P!fg!l!p!v!|#SSSOTTZR[XRORT[XQORT[QbUQncQulQysR|{ZaUcls{Z_Ucls{QxoRztTYR[QeWRriQTOR]TQ[RRj[QgYRpg",
  nodeNames:
    "⚠ LineComment Source Block Declaration Lemma Identifier Expression Value Keyword Binop Type Action Tactic Final",
  maxTerm: 33,
  skippedNodes: [0, 1],
  repeatNodeCount: 3,
  tokenData:
    "#h~RZXYtYZt]^tpqt|}!V}!O![!O!P!g!P!Q!l![!]#T!c!}#Y#T#o#Y~ySd~XYtYZt]^tpqt~![Oo~~!_P!`!a!b~!gOY~~!lOe~~!qSP~OY!lZ;'S!l;'S;=`!}<%lO!l~#QP;=`<%l!l~#YOi~~#_RU~!Q![#Y!c!}#Y#T#o#Y",
  tokenizers: [0],
  topRules: { Source: [0, 2] },
  specialized: [{ term: 6, get: (value) => spec_Identifier[value] || -1 }],
  tokenPrec: 0,
});
