name: Deploy website

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build endive-wasm NPM package
        run: wasm-pack build --target web
        working-directory: crates/endive-wasm
      - name: Use latest LTS Node.js release
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install npm dependencies
        run: npm ci
      - name: Build editor
        run: npm run build --workspace=packages/editor
      - name: Build endive-playground
        run: npm run build --workspace=endive-playground
      - name: Build website
        run: npm run build --workspace=packages/website
      - name: Set up WireGuard tunnel to HTTP server
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: 51.178.80.32:54720
          endpoint_public_key: /twfCY6i9x9pH7jP2HsDvPc9QDVuW2eaIxC84LaQ2xY=
          ips: 192.168.0.3/32
          allowed_ips: 192.168.0.1/32
          private_key: '${{ secrets.WG_PRIVATE_KEY }}'
          preshared_key: '${{ secrets.WG_PRESHARED_KEY }}'
      - name: Deploy endiveonline.fr
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
          ARGS: "-rlc --delete"
          SOURCE: "packages/website/dist/"
          REMOTE_HOST: 192.168.0.1
          REMOTE_USER: endive
          TARGET: /home/endive/endiveonline.fr
      - name: Deploy editor.endiveonline.fr
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
          ARGS: "-rlc --delete"
          SOURCE: "packages/editor/dist/"
          REMOTE_HOST: 192.168.0.1
          REMOTE_USER: endive
          TARGET: /home/endive/editor.endiveonline.fr
      - name: Deploy playground.endiveonline.fr
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
          ARGS: "-rlc --delete"
          SOURCE: "endive-playground/dist/"
          REMOTE_HOST: 192.168.0.1
          REMOTE_USER: endive
          TARGET: /home/endive/playground.endiveonline.fr

